<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?php echo base_url('assets/css/home.css') ?>">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light"
		th:fragment="dashboard-navbar(brand, role, activePage)">
		<div class="container">
      <a class="navbar-brand" href="<?php echo site_url('where_isclass/Home') ?>">Where is my classroom</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  			<div class="collapse navbar-collapse" id="navbarNav">
  				<ul class="navbar-nav mr-auto">
  					<li>
  						<a href="<?php echo site_url('where_isclass/User') ?>" class="nav-link">Minhas Turmas</a>
  					</li>
  				</ul>

  				<ul class="navbar-nav ml-auto">
  					<li class="nav-item"><span class="navbar-text"></li>
  					<li class="nav-item pl-3">
  					</li>
  				</ul>
  			</div>
  		</div>
  </nav>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <div class="form-row">
        <div class="col-md-10">
          <?php echo form_open('where_isclass/User/searchTurma'); ?>
            <input class="form-control" name="search">
        </div>
        <div class="col-md-1">
          <?php echo form_submit('', 'Procurar', "class='btn btn-primary'"); ?>
          <?php echo form_close(); ?>
          <!-- <button class="btn btn-primary">Procurar</button> -->
        </div>
    </div>
    </div>
  </div>
  <div class="row mt-4 justify-content-center">

    <div class="col-md-12">
      <div class="card-columns">
        <?php if(!empty($this->session->userdata('table'))):
          $table = $this->session->userdata('table'); ?>
        <?php foreach($table as $row) : ?>
          <?php $dias = explode(", ", $row["dia"])?>
					<?php $hini = explode(", ", $row["horarios_ini"])?>
					<?php $hfim = explode(", ", $row["horarios_fim"])?>
					<?php $salas = explode(", ", $row["sala"])?>
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">
								<?php echo $row["materia"] ?>
							</h3>
							<h6 class="card-subtitle mb-1 text-muted">
								<?php echo $row["professor"] ?>
							</h6>
							<h6 class="card-subtitle mb-4 text-muted">
								<?php echo $row["prof_email"]?>
							</h6>
							<p class="card-text">
								<?php echo $row["campus"] . ' - ' . $row["predio"] ?>
							</p>
							<?php if (sizeof($dias) > 1 && (sizeof($hini) > 1 || sizeof($hfim) > 1)) : ?>
								<p class="card-text">
									<?php echo $dias[0] . ': ' . $hini[0] . ' - ' . $hfim[0] ?>
								</p>
								<p class="card-text">
									<?php echo $dias[1] . ': ' . $hini[1] . ' - ' . $hfim[1] ?>
								</p>
							<?php else: ?>
								<p class="card-text">
									<?php echo $row["dia"] ?>
								</p>
								<p class="card-text">
									<?php echo $row["horarios_ini"] . ' - ' . $row["horarios_fim"] ?>
								</p>
							<?php endif ?>
							<p class="card-text">
								<?php echo $row["sala"] ?>
							</p>
              <p class="card-text">
								<?php echo 'Turma: ' . $row["turma"] ?>
							</p>
              <a href="#" class="card-link">Google Maps</a>
              <p><?php echo $row['maps']?></p>
            </div>
          </div>

      <?php endforeach; ?>
      <?php //$table[] = '' ?>
      <?php endif; ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

</body>
</html>
