	<?php $this->load->view("where_isclass/admin/menu");?>
	
	<div class="container mt-4">

		<div class="row justify-content-center">
			<div class="col-md-12">
				<div class="registration-form card">
					<div class="card-body">
						<h3 class="card-title">
						<?php 
							$class = '';
							if(!empty($turma)){
								$class = $turma[0];
							}
							$verb = '';
							if ($action == 'editar'){
								$verb = "Editar ";
								$actionUrl = 'where_isclass/admin/editTurma';
							} else if ($action == 'criar'){
								$verb = "Criar ";
								$actionUrl = 'where_isclass/admin/createTurma';
							};
						?>
						<?php echo $verb ?>Turma
						</h3>
						<div class="card-text">

							<!-- <form autocomplete="off" action="#" th:action="@{/registration-company}" th:object="${company}" method="post" class="form" role="form"> -->
							<?php echo form_open($actionUrl) ?>

							<input type="text" name="id" value="<?php if($action == 'editar') echo $class["id"] ?>" hidden />

								<div class="form-row">
									<div class="form-group col-md-4">
										<label for="teacher-select">Professor</label>
										<select class="custom-select" id="teacher-select"  name="teacher_id" required>
											<?php echo $teacherDropdown ?>
										</select>
									</div>
									<!-- TODO implementar ajax para pegar matéria de acordo com o professor -->
									<div class="form-group col-md-4">
										<label for="subject-select">Matéria</label>
										<select class="custom-select" id="subject-select" name="subject_id" required>
											<?php echo $subjectDropdown ?>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="period-select">Período</label>
										<select class="custom-select" id="period-select" name="period_id" required>
											<?php echo $periodDropdown ?>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="turma-select">Turma</label>
										<input type="text" placeholder="EX.: A1" class="form-control" id="turma-input" name="turma" required />
									</div>
								</div>
								<hr />
								<div class="form-row">
									<div class="form-group col-md-4">
										<label for="campus-select">Campus</label>
										<select class="custom-select" id="campus-select" name="campus_id" required>
											<?php echo $campusDropdown ?>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="building-select">Prédio</label>
										<select class="custom-select" id="building-select" name="building" required>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="name-input">Endereço</label>
										<input type="text" placeholder="Rua Das Coves" class="form-control" id="address-input" name="address" required readonly />
									</div>
									<div class="form-group col-md-4">
										<label for="name-input">Google Maps</label>
										<input type="textarea" placeholder="iFrame do Google Maps pequeno" class="form-control" id="maps_info" name="maps_info" required readonly />
									</div>
								</div>
								<hr />
								<div class="form-row">
								<div class="form-group col-md-4">
										<label for="schedule-select">Horários Diferentes</label>
										<select class="custom-select" id="schedule-select" name="schedule-select">
											<option selected value="1">1</option>
											<option value="2">2</option>
										</select>
									</div>
								</div>

								<div class="form-row">
									<div class="col-md-6 form-group mt-4">
										<div class="form-check form-check-inline ">
											<input class="form-check-input" type="checkbox" name="weekDayOptions1" id="firstWeekDay1" value="1">
											<label class="form-check-label" for="firstWeekDay1">Segunda</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions2" id="firstWeekDay2" value="2">
											<label class="form-check-label" for="firstWeekDay2">Terça</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions3" id="firstWeekDay3" value="3">
											<label class="form-check-label" for="firstWeekDay3">Quarta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions4" id="firstWeekDay4" value="4">
											<label class="form-check-label" for="firstWeekDay4">Quinta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions5" id="firstWeekDay5" value="5">
											<label class="form-check-label" for="firstWeekDay5">Sexta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions6" id="firstWeekDay6" value="6">
											<label class="form-check-label" for="firstWeekDay6">Sábado</label>
										</div>
									</div>
									<div class="form-group col-md-2">
										<label for="name-input">Horário de Início</label>
										<input type="time" placeholder="18:00" class="form-control" id="start-time-input" name="start_time" required />
										<br/>
										<label for="name-input">Sala</label>
										<input type="text" placeholder="Número da Sala" class="form-control" id="room-input" name="room" required />
									</div>
									<div class="form-group col-md-2">
										<label for="name-input">Horário de Término</label>
										<input type="time" placeholder="20:00" class="form-control" id="end-time-input" name="end_time" required />
										<br/>
									</div>
								</div>
								<br/>
								<div class="form-row" id="second-row">
									<div class="col-md-6 form-group mt-4">
										<div class="form-check form-check-inline ">
											<input class="form-check-input" type="checkbox" name="2weekDayOptions1" id="2firstWeekDay1" value="1">
											<label class="form-check-label" for="2firstWeekDay1">Segunda</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="2weekDayOptions2" id="2firstWeekDay2" value="2">
											<label class="form-check-label" for="2firstWeekDay2">Terça</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="2weekDayOptions3" id="2firstWeekDay3" value="3">
											<label class="form-check-label" for="2firstWeekDay3">Quarta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="2weekDayOptions4" id="2firstWeekDay4" value="4">
											<label class="form-check-label" for="2firstWeekDay4">Quinta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="2weekDayOptions5" id="2firstWeekDay5" value="5">
											<label class="form-check-label" for="2firstWeekDay5">Sexta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="2weekDayOptions6" id="2firstWeekDay6" value="6">
											<label class="form-check-label" for="2firstWeekDay6">Sábado</label>
										</div>
									</div>
									<div class="form-group col-md-2">
										<label for="name-input">Horário de Início</label>
										<input type="time" placeholder="18:00" class="form-control" id="2start-time-input" name="2start_time" required />
										<br/>
										<label for="name-input">Sala</label>
										<input type="text" placeholder="Número da Sala" class="form-control" id="2room-input" name="2room"  />
									</div>
									<div class="form-group col-md-2">
										<label for="name-input">Horário de Término</label>
										<input type="time" placeholder="20:00" class="form-control" id="2end-time-input" name="2end_time" required />
										<br/>
									</div>
								</div>

								<hr />
								<div class="form-row">
									<div class="form-group col-md-12">
										<?php echo form_submit('', 'Salvar', "class='btn btn-primary btn-block'") ?>
									</div>
								</div>
								<?php echo form_close() ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
			<?php //var_dump($class)?>

	<script>
		var teacher = document.getElementById('teacher-select');
		var teacherCount = teacher.options.length;
		var subject = document.getElementById('subject-select');
		var subjectCount = subject.options.length;
		var period = document.getElementById('period-select');
		var periodCount = period.options.length;
		var turma = document.getElementById('turma-input');
		var campus = document.getElementById('campus-select');
		var campusCount = campus.options.length;
		var endereco = document.getElementById('address-input');
		var maps = document.getElementById('maps_info');
		var horario_ini = document.getElementById('start-time-input');
		var horario_fim = document.getElementById('end-time-input');
		var schedule = document.getElementById("schedule-select");

		<?php if (!empty($class)): ?>
		for (var i=0; i<teacherCount; i++){
			if(teacher.options[i].innerHTML == "<?php echo $class['professor'] ?>"){
				teacher.options[i].selected = true;
				break;
			}
		}
		for (var i=0; i<subjectCount; i++) {
			if (subject.options[i].innerHTML == "<?php echo $class['materia'] ?>") {
				subject.options[i].selected = true;
				break;
			}
		}
		for (var i=0; i<periodCount; i++) {
			if (period.options[i].innerHTML == "<?php echo $class['periodo'] ?>") {
				period.options[i].selected = true;
				break;
			}
		}
		for (var i=0; i<campusCount; i++) {
			if (campus.options[i].innerHTML == "<?php echo $class['campus'] ?>") {
				campus.options[i].selected = true;
				break;
			}
		}
		turma.value = "<?php echo $class['turma']?>";
		
		<?php
		$dias = explode(", ", $class['dia']);
		$salas = explode(', ', $class['sala']);
		$hini = explode(", ", $class["horarios_ini"]);
		$hfim = explode(", ", $class["horarios_fim"]);
		$optionDia[] = '';
		$i = 0;
		for($i = 0; $i < count($dias); $i++): 
			if (count($salas) == 1 || $i == 0): ?>
				checkBoxes("<?php echo $dias[$i]?>","");
			<?php elseif($i == 1):?>
				(checkBoxes("<?php echo $dias[$i]?>", "2"))
			<?php endif;?>
		<?php endfor; ?>
		endereco.value = "<?php echo $class['endereco'] ?>";
		
		var salas = "<?php echo count($salas) ?>" ;
		var hini = "<?php echo count($hini)?>";
		var hfim = "<?php echo count($hfim)?>";
		horario_ini.value = "<?php echo $hini[0] ?>";
		horario_fim.value = "<?php echo $hfim[0] ?>";
		if (hini > 1 || hfim > 1){
			document.getElementById('2start-time-input').value = "<?php echo (isset($hini[1]) ? $hini[1] : '') ?>";
			document.getElementById('2end-time-input').value = "<?php echo (isset($hfim[1]) ? $hfim[1] : '') ?>";
		} else if (salas > 1){
			document.getElementById('2start-time-input').value = "<?php echo $hini[0] ?>";
			document.getElementById('2end-time-input').value = "<?php echo $hfim[0] ?>";
		}

		document.getElementById('room-input').value = "<?php echo $salas[0] ?>";
		if (salas > 1){
			document.getElementById('2room-input').value = "<?php echo (isset($salas[1]) ? $salas[1] : '') ?>";
			schedule.value = 2;
		} else {segundoHorario();}
		maps.value = '<?php echo $class['maps'] ?>';

		<?php endif;?>
		schedule.addEventListener('change', function(event){
			segundoHorario();
		}, false);
		function segundoHorario(){
			var linha = document.querySelector('#second-row');
			var schedule = document.querySelector('#schedule-select');
			if (schedule.value == 1){
				linha.style.display = "none";
				document.getElementById('2start-time-input').required = false;
				document.getElementById('2end-time-input').required = false;
				document.getElementById('2firstWeekDay1').checked = true;
			} else {
				linha.style.display = "flex";
				document.getElementById('2start-time-input').value = '';
				document.getElementById('2end-time-input').value = '';
				for(i = 1; i <= 6; i++){
					var c = '2firstWeekDay';
					c += i;
					document.getElementById(c).checked = false;
				}
			}
		}

		campus.addEventListener('change', function(){
			changeCampus();
		});
		function changeCampus(){
			var campusId = campus.selectedIndex;
			var selected = '';
			$.ajax({
				url: '/solicitasi/addressesDrop/ajax',
				method: 'post',
				data: {campusId: campusId},
				dataType: 'json',
				success:function(response){
					$('select[name="building"]').empty();
					$('select[name="building"]').append('<option value ="0">Selecione o Prédio </option>');
                    $.each(response, function(key, value){
						if ("<?php echo $action?>" != "criar" && value.building == "<?php echo isset($class['predio']) ? $class['predio'] : '' ?>" ){
							selected = 'selected';
						}
                        $('select[name="building"]').append('<option value ="' + value.id + '"' + selected + '>' + value.building + '</option>');
						selected = '';
					});
				}
			});
		}
		function checkBoxes(dia, number){
			if (dia == "Segunda"){
				document.getElementById(number+'firstWeekDay1').checked = true;
			} else if (dia == "Terça"){
				document.getElementById(number+'firstWeekDay2').checked = true;
			} else if (dia == "Quarta"){
				document.getElementById(number+'firstWeekDay3').checked = true;
			}else if (dia == "Quinta"){
				document.getElementById(number+'firstWeekDay4').checked = true;
			}else if (dia == "Sexta"){
				document.getElementById(number+'firstWeekDay5').checked = true;
			}else if (dia == "Sábado"){
				document.getElementById(number+'firstWeekDay6').checked = true;
			}
		}

		var building = document.getElementById('building-select');
		building.addEventListener('change', function(event){
			var campusId = campus.selectedIndex;
			var buildingId = building.selectedIndex;
			var buildingText = building.options[buildingId].text;
			$.ajax({
				url: '/solicitasi/addressesDrop/ajax',
				method: 'post',
				data: {campusId: campusId},
				dataType: 'json',
				success:function(response){
					$.each(response, function(key, value){
						if (buildingText == value.building){
							endereco.value = value.address;
							maps.value = value.iframe;
						}
					});
				}
			});
		});
		window.onload = function(){
			<?php if (empty($class)): ?>
				segundoHorario();
			<?php endif?>
			changeCampus();
		} 
	</script>