	<?php $this->load->view("where_isclass/admin/menu");?>
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-12">
				<div class="form-row justify-content-center">
					<div class="col-md-10">
						<?php echo form_open('where_isclass/Admin/searchHome'); ?>
						<input class="form-control" name="search">
					</div>
					<div class="col-md-1">
						<?php echo form_submit('', 'Procurar', "class='btn btn-primary'"); ?>
						<?php echo form_close(); ?>
					</div>
					<div class="col-md-1">
						<a type="button" class="btn btn-success" href="<?php echo site_url('where_isclass/Admin/classroom/'. $id = -1 .'/criar') ?>">Criar</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row mt-4 justify-content-center">

			<div class="col-md-12">
				<div class="card-columns">
					<?php if(!empty($table)): ?>
					<?php foreach($table as $row) : ?>
					<?php $dias = explode(", ", $row["dia"]) ?>
					<?php $hini = explode(", ", $row["horarios_ini"])?>
					<?php $hfim = explode(", ", $row["horarios_fim"])?>
					<?php $salas = explode(", ", $row["sala"])?>
					<div class="card">
						<div class="card-body">
							<h3 class="card-title">
								<?php echo $row["materia"] ?>
							</h3>
							<h6 class="card-subtitle mb-1 text-muted">
								<?php echo $row["professor"] ?>
							</h6>
							<h6 class="card-subtitle mb-4 text-muted">
								<?php echo $row["prof_email"]?>
							</h6>
							<p class="card-text">
								<?php echo $row["campus"] . ' - ' . $row["predio"] ?>
							</p>
							<?php if (sizeof($dias) > 1 && (sizeof($hini) > 1 || sizeof($hfim) > 1)) : ?>
								<p class="card-text">
									<?php echo $dias[0] . ': ' . $hini[0] . ' - ' . $hfim[0] ?>
								</p>
								<p class="card-text">
									<?php echo $dias[1] . ': ' . $hini[1] . ' - ' . $hfim[1] ?>
								</p>
							<?php else: ?>
								<p class="card-text">
									<?php echo $row["dia"] ?>
								</p>
								<p class="card-text">
									<?php echo $row["horarios_ini"] . ' - ' . $row["horarios_fim"] ?>
								</p>
							<?php endif ?>
							<p class="card-text">
								<?php echo $row["sala"] ?>
							</p>
							<p class="card-text">
								<?php echo 'Turma: ' . $row["turma"] ?>
							</p>
							<a type="button" class="btn btn-success" href="<?php echo site_url('where_isclass/admin/classroom/'.$row["id"].'/editar') ?>">Editar</a>
							<a type="button" class="btn btn-danger" href="<?php echo site_url('where_isclass/admin/deleteTurma/'.$row["id"])?>">Excluir</a>
						</div>
					</div>

					<?php endforeach; ?>
					<?php //$table[] = '' ?>
					<?php endif; ?>

				</div>
			</div>
		</div>
	</div>

	<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
	<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
	<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>