	<?php $this->load->view("where_isclass/admin/menu");?>

	<div class="container mt-4">
		<div class="row">
			<div class="col-md-12">
				<div class="form-row justify-content-center">
					<div class="col-md-10">
						<?php echo form_open('where_isclass/admin/searchTeachers'); ?>
						<input class="form-control" name="search">
					</div>
					<div class="col-md-1">
						<?php echo form_submit('', 'Procurar', "class='btn btn-primary'"); ?>
						<?php echo form_close(); ?>
					</div>
					<div class="col-md-1">
						<button type="button" data-js="create-button" class="btn btn-success">Criar</button>
					</div>
				</div>
			</div>
		</div>
		<div class="row mt-4 justify-content-center">

			<div class="col-md-12">
				<div class="list-group">
				<?php if (!empty($table)): ?>
					<?php foreach ($table as $row): ?>
					<a href="#" class="list-group-item list-group-item-action flex-column align-items-start" data-toggle="modal" data-target="#exampleModalCenter">
						<div class="d-inline-flex justify-content-between">
							<h5 class="mb-1" data-js="teacher-name"><?php echo $row->name ?></h5>
						</div>
						<p class="mb-1" data-js="teacher-email"><?php echo $row->email ?></p>
						<p data-js="id" hidden><?php echo $row->id ?></p>
					</a>
					<?php endforeach;?>
				<?php endif;?>

				</div>
			</div>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="modal-title">Criar Novo Professor</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<?php echo form_open_multipart('where_isclass/admin/modalTeacher', 'id="form-modal"') ?>
						<input name="action" id="action" hidden/>
						<div class="form-group">
							<label for="name">Nome</label>
							<input class="form-control" type="text" name="name" placeholder="Nome" required>
						</div>
						<div class="form-group">
							<label for="email">Email</label>
							<input class="form-control" type="text" id="email" name="email" placeholder="Email" required>
						</div>
						<input name="id" hidden>
						<div class="modal-footer">
							<?php echo form_submit('', 'Deletar', 'data-js="delete-button", class="btn btn-danger mr-auto", id="bDelete"') ?>
							<?php echo form_submit('', 'Salvar', 'class="btn btn-primary", id="bSave"') ?>
						</div>
					<?php echo form_close() ?>
				</div>
			</div>
		</div>
  </div>

		<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
		<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
		<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

    <script>
      (function($) {
        var modal = $('.modal').first();

        var deleteButton = modal.find('[data-js="delete-button"]').first();

        var modalTitle = modal.find('#modal-title').first();
				var modalIdInput = modal.find('.modal-body input[name="id"]').first();
        var modalNameInput = modal.find('.modal-body input[name="name"]').first();
				var modalEmailInput = modal.find('.modal-body input[name="email"]').first();

        function resetInput(){
          modalTitle.text('Criar Novo Professor');
          modal.find('form')[0].reset();
        }

        //add button clicked
        $('[data-js="create-button"').click(function(){
					resetInput();
					deleteButton.hide();
					modal.modal('show');
					var action = document.getElementById('action');
					action.value = 'create';
        });


        //list item clicked
        $('.list-group-item').click(function() {
        	deleteButton.show();
        			var elem = $( this );
					var id = elem.find('[data-js="id"]').text();
        			var teacherName = elem.find('[data-js="teacher-name"]').text()
					var teacherEmail = elem.find('[data-js="teacher-email"]').text()
					var action = document.getElementById('action');
					var bSave = document.getElementById('bSave');
					var bDelete = document.getElementById('bDelete');
					bSave.addEventListener('click', function(){
						action.value = 'edit'
					});
					bDelete.addEventListener('click', function(){
						document.getElementById('email').required = false;
						action.value = 'delete'
					});
					modalTitle.text(teacherName);
					modalNameInput.val(teacherName);
					modalIdInput.val(id);
					modalEmailInput.val(teacherEmail);
        });

      })(jQuery);
    </script>